### ISSUE TITLE
User Code Upload

### ISSUE THREAD

**Issue by IamRaviTejaG-zz** [p-society/Online-Judge#1]
@knrt10 @palash25 @ayush1999 

Here's the initial code. This works when small snippets of code are passed with mime-type `application/json`. The server assumes that the user's code is received via a JSON in the "content" key.

@knrt10 Please help with the file upload part so that the user can upload files. Further, how can we send text from a text field with proper indentation (say, the user submits a Python code snippet, we ought to retain the indentation)?!

**Comment by knrt10** [comment]
@IamRaviTejaG avoid using templates. Cause this is going to be a big project and it will really get confusing for writing **front end**. I would suggest please use any framework like **angular** or **react**. And I would suggest when you upload a code write tests along with it. We would try to implement TDD(For node part).

**Comment by knrt10** [comment]
And I would suggest try **mongoDB** for database. When we will be setting database for questions we won't have to rely on localhost our database will be hosted online **mlab** give free hosting for 500mb and I don't think questions will exceed size greater than that. Rest its up to you if you wanna suggest anything else, I am cool with that. Mine is just a suggestion.

**Comment by knrt10** [comment]
@palash25 @ayush1999 @IamRaviTejaG Let's first discuss structure of app. Which languages/framework you all wanna use?

**Comment by IamRaviTejaG-zz** [comment]
@knrt10 Yeah, templates feel like everything's hard-coded.

How about we discuss the tech-stack and the approach?!

**Comment by knrt10** [comment]
Please feel free to comment cause this project will be successful if all pitch in and everybody is satisfied by tech-stack

**Comment by palash25** [comment]
When did all this happen? :laughing: 

> How about we discuss the tech-stack and the approach?!

You are already using JS to write the server so I guess you want to write the whole thing in Node. I'm fine with that.

The frontend could be debatable.
Angular or React @IamRaviTejaG @knrt10 you guys decide.

**Comment by knrt10** [comment]
@palash25 You sure?

**Comment by knrt10** [comment]
@IamRaviTejaG you cool with angular?

**Comment by IamRaviTejaG** [comment]
@knrt10 With the idea, yes. Need to learn Angular though. 😅

**Comment by knrt10** [comment]
React?

**Comment by anishsarangi** [comment]
@IamRaviTejaG @knrt10 You can go with React. It will be better.

**Comment by IamRaviTejaG** [comment]
@knrt10 Cool with react.

**Comment by IamRaviTejaG-zz** [comment]
Sorry for the that close and open.

**Comment by sr6033** [comment]
Also upload a readme for others so that all can contribute.

**Comment by palash25** [comment]
closed because changes will be made in code.
