### ISSUE TITLE
Considering DMOJ

### ISSUE THREAD

**Issue by bkhanale** [p-society/Online-Judge#2]
Is it still work in progress? I was thinking about using [DMOJ](https://github.com/DMOJ) for the judging purposes. Since there are plenty of open source judges already available, we could save some time using them instead of constructing one ourselves.

@IamRaviTejaG @palash25 @knrt10

**Comment by knrt10** [comment]
We are not currently working on this issue and if anyone wants to implement they can. cc @bkhanale

**Comment by bkhanale** [comment]
No, I was thinking of using their both front-end and back-end for our local offline contests. Since the idea of creating of new judge is now deprecated.
